"""alteração da coluna paidAt para nullable

Revision ID: b1dd599bcc63
Revises: e3fade3ac9a5
Create Date: 2025-02-17 12:35:40.374825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1dd599bcc63'
down_revision = 'e3fade3ac9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('paidAt',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('paidAt',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
