"""criação das colunas category, paidAt e dueAt

Revision ID: e3fade3ac9a5
Revises: 05c3a64a4f0f
Create Date: 2025-02-17 12:22:55.021025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fade3ac9a5'
down_revision = '05c3a64a4f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('paidAt', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('dueAt', sa.DateTime(), nullable=False))
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('dueAt')
        batch_op.drop_column('paidAt')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
